name: CI

on:
  push:
    branches: [ "main" ] # or "master", adjust to your default branch
  pull_request:
    branches: [ "main" ] # or "master", adjust to your default branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Or your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests (if you have them)
      run: npm test # Or your test command. If you dont have tests remove this line.

    - name: Build
      run: npm run build # Or your build command.